use super::preset::Preset;

/// Factory preset JSON, embedded into the binary at compile time via
/// `include_str!` rather than read from disk at runtime. This is deliberate:
/// Android has no ordinary filesystem path to a bundled `assets/` directory
/// (it requires the NDK asset manager, a different API entirely), so baking
/// the content into the binary is the one loading strategy that works
/// identically on desktop and Android. Regenerate these files with
/// `cargo run -p guitar_desktop --bin generate_factory_presets`.
const FACTORY_PRESET_JSON: &[&str] = &[
    include_str!("../../assets/presets/factory/clean_jazz.json"),
    include_str!("../../assets/presets/factory/blues_crunch.json"),
    include_str!("../../assets/presets/factory/rock_lead.json"),
    include_str!("../../assets/presets/factory/metal_high_gain.json"),
    include_str!("../../assets/presets/factory/ambient_ping-pong.json"),
    include_str!("../../assets/presets/factory/funk_wah.json"),
    include_str!("../../assets/presets/factory/classic_rock_rhythm.json"),
    include_str!("../../assets/presets/factory/shoegaze_wall.json"),
    include_str!("../../assets/presets/factory/country_twang.json"),
    include_str!("../../assets/presets/factory/surf_rock.json"),
    include_str!("../../assets/presets/factory/funk_envelope.json"),
    include_str!("../../assets/presets/factory/doom_sludge.json"),
    include_str!("../../assets/presets/factory/pop_clean.json"),
    include_str!("../../assets/presets/factory/reggae_skank.json"),
    include_str!("../../assets/presets/factory/acoustic_simulation.json"),
    include_str!("../../assets/presets/factory/lo-fi_tape.json"),
    include_str!("../../assets/presets/factory/synth_lead.json"),
    include_str!("../../assets/presets/factory/rockabilly_slapback.json"),
    include_str!("../../assets/presets/factory/metal_djent.json"),
    include_str!("../../assets/presets/factory/ambient_pad_looper.json"),
];

/// Parses every embedded factory preset. Malformed entries are skipped rather
/// than panicking -- this list is regenerated by a maintenance tool and
/// checked into the repo as plain files, so a bad entry should degrade
/// gracefully rather than crash the app at startup.
pub fn factory_presets() -> Vec<Preset> {
    let mut presets: Vec<Preset> = FACTORY_PRESET_JSON
        .iter()
        .filter_map(|json| serde_json::from_str(json).ok())
        .collect();
    presets.sort_by(|a, b| a.name.cmp(&b.name));
    presets
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_embedded_factory_preset_parses() {
        let presets = factory_presets();
        assert_eq!(
            presets.len(),
            FACTORY_PRESET_JSON.len(),
            "one or more factory preset JSON files failed to parse"
        );
    }

    #[test]
    fn factory_presets_have_unique_names() {
        let presets = factory_presets();
        let mut names: Vec<&str> = presets.iter().map(|p| p.name.as_str()).collect();
        let unique_count = {
            names.sort_unstable();
            names.dedup();
            names.len()
        };
        assert_eq!(unique_count, presets.len(), "factory preset names must be unique");
    }
}
